Repository opendevstack/ods-jenkins-shared-library, pull requests merged in 2020-04, with the labels that each got.

#220 mro fixes master - forward port master
  src/org/ods/Context.groovy
  src/org/ods/OdsContext.groovy
  src/org/ods/OdsPipeline.groovy
Labels: enhancement

#223 bug - shared lib version missing because of wrong name -> 2.x
  src/org/ods/OdsContext.groovy
Labels: bug

#226 Convert SonarQube stage to new style
  src/org/ods/component/Pipeline.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/services/OpenShiftService.groovy
  src/org/ods/services/SonarQubeService.groovy
  test/groovy/vars/OdsComponentStageScanWithSonarSpec.groovy
  vars/odsComponentStageScanWithSonar.groovy
  vars/stageScanForSonarqube.groovy
Labels: enhancement

#232 Feature/add image labels and fix broken debug
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/Context.groovy
  src/org/ods/component/IContext.groovy
  test/groovy/org/ods/PipelineScript.groovy
  vars/odsComponentPipeline.groovy
Labels: bug

#234 Specify credentials/URL explicitly
  src/org/ods/component/Pipeline.groovy
Labels: bug

#228 Convert Snyk stage to new style
  src/org/ods/component/Context.groovy
  src/org/ods/component/ScanWithSnykStage.groovy
  src/org/ods/services/SnykService.groovy
  test/groovy/vars/OdsComponentStageScanWithSnykSpec.groovy
  vars/odsComponentStageScanWithSnyk.groovy
  vars/stageScanForSnyk.groovy
Labels: enhancement

#235 Allow to configure "imageStreamTag" instead of "image"
  src/org/ods/component/Context.groovy
Labels: enhancement

#237 Feature/add image labels - the old shell version
  src/org/ods/component/Context.groovy
Labels: enhancement

#236 Fix build args patches
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/services/OpenShiftService.groovy
Labels: bug

#230 Add quickstarter pipeline
  src/org/ods/quickstarter/CheckoutStage.groovy
  src/org/ods/quickstarter/Context.groovy
  src/org/ods/quickstarter/CopyFilesStage.groovy
  src/org/ods/quickstarter/CreateOpenShiftResourcesStage.groovy
  src/org/ods/quickstarter/CreateOutputDirectoryStage.groovy
  src/org/ods/quickstarter/IContext.groovy
  src/org/ods/quickstarter/Pipeline.groovy
  src/org/ods/quickstarter/PushToRemoteStage.groovy
  src/org/ods/quickstarter/RenderJenkinsfileStage.groovy
  src/org/ods/quickstarter/RenderSonarPropertiesStage.groovy
  src/org/ods/quickstarter/Stage.groovy
  test/groovy/vars/OdsQuickstarterStageCopyFilesSpec.groovy
  test/groovy/vars/OdsQuickstarterStageCreateOpenShiftResources.groovy
  test/groovy/vars/OdsQuickstarterStageRenderJenkinsfileSpec.groovy
  test/groovy/vars/OdsQuickstarterStageRenderSonarPropertiesSpec.groovy
  vars/odsQuickstarterPipeline.groovy
  vars/odsQuickstarterStageCopyFiles.groovy
  vars/odsQuickstarterStageCreateOpenShiftResources.groovy
  vars/odsQuickstarterStageRenderJenkinsfile.groovy
  vars/odsQuickstarterStageRenderSonarProperties.groovy
Labels: enhancement

#242 Feature/add mono repo support
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/Context.groovy
  src/org/ods/component/IContext.groovy
  src/org/ods/component/Pipeline.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/component/ScanWithSnykStage.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/component/Stage.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
  vars/odsComponentStageBuildOpenShiftImage.groovy
  vars/odsComponentStageRolloutOpenShiftDeployment.groovy
  vars/withStage.groovy
Labels: enhancement

#264 More docs for quickstarter pipeline
  docs/modules/jenkins-shared-library/pages/component-pipeline.adoc
  docs/modules/jenkins-shared-library/pages/quickstarter-pipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentPipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageBuildOpenShiftImage.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageRolloutOpenShiftDeployment.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSnyk.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSonar.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterPipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterStageCopyFiles.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterStageCreateOpenShiftResources.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterStageRenderJenkinsfile.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterStageRenderSonarProperties.adoc
Labels: documentation

#270 refactor uploadToNexusStage to new stage architecture
  docs/modules/jenkins-shared-library/pages/component-pipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageUploadToNexus.adoc
  src/org/ods/component/Context.groovy
  src/org/ods/component/Pipeline.groovy
  src/org/ods/component/UploadToNexusStage.groovy
  test/groovy/org/ods/PipelineScript.groovy
  test/groovy/vars/OdsComponentStageUploadToNexusSpec.groovy
  test/groovy/vars/StageUploadToNexusSpec.groovy
  vars/odsComponentStageUploadToNexus.groovy
  vars/stageUploadToNexus.groovy
Labels: enhancement

#283 Update orchestration pipeline docs
  docs/modules/jenkins-shared-library/nav.adoc
  docs/modules/jenkins-shared-library/pages/index.adoc
  docs/modules/jenkins-shared-library/pages/orchestration-pipeline.adoc
  promotion-guide.adoc
Labels: documentation

#287 Merge service registries
  src/org/ods/component/Pipeline.groovy
  src/org/ods/orchestration/BuildStage.groovy
  src/org/ods/orchestration/DeployStage.groovy
  src/org/ods/orchestration/FinalizeStage.groovy
  src/org/ods/orchestration/InitStage.groovy
  src/org/ods/orchestration/ReleaseStage.groovy
  src/org/ods/orchestration/Stage.groovy
  src/org/ods/orchestration/TestStage.groovy
  src/org/ods/orchestration/service/ServiceRegistry.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  test/groovy/org/ods/services/ServiceRegistrySpec.groovy
Labels: enhancement

#284 Feature/contributor fixes
  Jenkinsfile
  docs/modules/jenkins-shared-library/pages/quickstarter-pipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterStageForkODS.adoc
  ocp-config/prov-cd/Tailorfile
  ocp-config/prov-cd/bc.yml
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/quickstarter/ForkFromGithubODSStage.groovy
  src/org/ods/quickstarter/PushToRemoteStage.groovy
  test/groovy/vars/OdsComponentStageScanWithSonarSpec.groovy
  vars/odsQuickstarterStageForkODS.groovy
Labels: enhancement

#289 bug / remote origin on initial commit fails
  src/org/ods/component/Pipeline.groovy
  src/org/ods/quickstarter/Context.groovy
  src/org/ods/quickstarter/IContext.groovy
  src/org/ods/quickstarter/Pipeline.groovy
Labels: bug
