Repository opendevstack/ods-jenkins-shared-library, pull requests merged in 2020-11, with the labels that each got.

#481 Add missing semicolon
  src/org/ods/quickstarter/RenderJenkinsfileStage.groovy
Labels: bug

#487 component pipeline: Fix concurrent builds - master
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
Labels: bug

#485 Update doc about partial rebuilds
  docs/modules/jenkins-shared-library/pages/orchestration-pipeline.adoc
Labels: documentation

#488 component pipeline: Fix concurrent builds (3.x)
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
Labels: bug

#492 Pass project to every method of OpenShiftService
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/ImportOpenShiftImageStage.groovy
  src/org/ods/component/Pipeline.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/orchestration/DeployStage.groovy
  src/org/ods/orchestration/FinalizeStage.groovy
  src/org/ods/orchestration/InitStage.groovy
  src/org/ods/orchestration/phases/DeployOdsComponent.groovy
  src/org/ods/orchestration/phases/FinalizeOdsComponent.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/orchestration/util/Project.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/org/ods/services/OpenShiftServiceSpec.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageImportOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
Labels: enhancement

#500 Support Deployment resources in component pipeline
  src/org/ods/component/Context.groovy
  src/org/ods/component/IContext.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/orchestration/phases/DeployOdsComponent.groovy
  src/org/ods/orchestration/phases/FinalizeOdsComponent.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/org/ods/services/OpenShiftServiceSpec.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
  vars/odsComponentStageImportOpenShiftImageOrElse.groovy
Labels: enhancement
