Repository opendevstack/ods-jenkins-shared-library, pull requests merged in 2020-05, with the labels that each got.

#307 Do not query for OpenShift app domain when no environment has been determined
  src/org/ods/component/Pipeline.groovy
Labels: bug

#301 fix Bitbucket not recognizing last successful build after a failed one
  src/org/ods/OdsPipeline.groovy
Labels: bug

#302 fix Bitbucket not recognizing last successful build after a failed one
  src/org/ods/component/Pipeline.groovy
Labels: bug

#312 Make ODS namespace configurable
  docs/modules/jenkins-shared-library/pages/quickstarter-pipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsQuickstarterPipeline.adoc
  src/org/ods/quickstarter/Context.groovy
  src/org/ods/quickstarter/IContext.groovy
  src/org/ods/quickstarter/Pipeline.groovy
Labels: enhancement

#335 Remove notification from not overall DTR
  src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
Labels: bug

#336 Various cleanup
  .github/workflows/gradle.yml
  build.gradle
  docs/modules/jenkins-shared-library/partials/odsComponentStageBuildOpenShiftImage.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageRolloutOpenShiftDeployment.adoc
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/Context.groovy
  src/org/ods/component/IContext.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/component/ScanWithSnykStage.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/component/Stage.groovy
  src/org/ods/component/UploadToNexusStage.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
  vars/stageOWASPDependencyCheck.groovy
Labels: enhancement

#337 Allow image URLs without registry
  src/org/ods/quickstarter/Context.groovy
  src/org/ods/quickstarter/CreateOpenShiftResourcesStage.groovy
  src/org/ods/services/OpenShiftService.groovy
  test/groovy/org/ods/services/OpenShiftServiceSpec.groovy
Labels: bug

#340 Ease and document Tailor-based preview deploy
  build.gradle
  docs/modules/jenkins-shared-library/pages/quickstarter-pipeline.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentPipeline.adoc
  src/org/ods/component/Context.groovy
  src/org/ods/component/IContext.groovy
  src/org/ods/component/Pipeline.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/services/GitService.groovy
  test/groovy/vars/OdsComponentStageScanWithSonarSpec.groovy
Labels: enhancement

#347 Encode userinfo part
  src/org/ods/orchestration/Stage.groovy
Labels: bug

#352 Fix various smaller issues
  src/org/ods/component/Pipeline.groovy
  src/org/ods/quickstarter/CreateOutputDirectoryStage.groovy
  src/org/ods/services/SonarQubeService.groovy
Labels: bug

#354 Add OpenShift project name to token name
  src/org/ods/services/BitbucketService.groovy
Labels: enhancement

#361 Expose Bitbucket URL
  src/org/ods/quickstarter/Context.groovy
  src/org/ods/quickstarter/IContext.groovy
  src/org/ods/quickstarter/Pipeline.groovy
Labels: bug

#360 Write update docs to 3.x
  docs/modules/jenkins-shared-library/partials/odsComponentPipeline.adoc
  docs/modules/jenkins-shared-library/partials/update-to-3x.adoc
Labels: documentation

#362 Expose DOCKER_REGISTRY
  src/org/ods/quickstarter/IContext.groovy
Labels: bug
