Repository opendevstack/ods-jenkins-shared-library, pull requests merged in 2021-05, with the labels that each got.

#638 Feature/id in test cycle results
  CHANGELOG.md
  src/org/ods/orchestration/usecase/JiraUseCaseZephyrSupport.groovy
  src/org/ods/orchestration/util/Project.groovy
  test/groovy/org/ods/orchestration/usecase/JiraUseCaseZephyrSupportSpec.groovy
Labels: enhancement

#641 added changelog enforcer (again)
  .github/workflows/changelog-enforcer.yml
Labels: documentation, skip changelog

#640 component pipeline: repo name dynamic - master
  src/org/ods/component/Pipeline.groovy
Labels: skip changelog

#642 Add comment pointing to Stage#execute method
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/ImportOpenShiftImageStage.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/component/ScanWithSnykStage.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/component/UploadToNexusStage.groovy
Labels: skip changelog

#649 Backport/add noncps
  CHANGELOG.md
  src/org/ods/orchestration/usecase/JiraUseCase.groovy
  src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
  src/org/ods/orchestration/util/DocumentHistory.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/orchestration/util/Project.groovy
  test/groovy/org/ods/orchestration/usecase/LeVADocumentUseCaseSpec.groovy
  test/groovy/org/ods/orchestration/util/ProjectSpec.groovy
  test/groovy/util/FixtureHelper.groovy
Labels: bug

#647 added noncps to avoid errors during document generation - 3.x
  src/org/ods/orchestration/usecase/JiraUseCase.groovy
  src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
  src/org/ods/orchestration/util/DocumentHistory.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/orchestration/util/Project.groovy
  test/groovy/org/ods/orchestration/usecase/LeVADocumentUseCaseSpec.groovy
  test/groovy/org/ods/orchestration/util/ProjectSpec.groovy
  test/groovy/util/FixtureHelper.groovy
Labels: bug

#646 Add labels to generated OpenShift resources
  CHANGELOG.md
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/openshift/OpenShiftResourceMetadata.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/quickstarter/CreateOpenShiftResourcesStage.groovy
  src/org/ods/services/OpenShiftService.groovy
  src/org/ods/util/IPipelineSteps.groovy
  src/org/ods/util/PipelineSteps.groovy
  test/groovy/org/ods/openshift/OpenShiftResourceMetadataSpec.groovy
  test/groovy/org/ods/services/OpenShiftServiceSpec.groovy
  test/groovy/util/OpenShiftHelper.groovy
  test/groovy/util/PipelineSteps.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
  test/groovy/vars/OdsQuickstarterStageCreateOpenShiftResources.groovy
  test/groovy/vars/OdsQuickstarterStageCreateOpenShiftResourcesSpec.groovy
Labels: enhancement
