Repository opendevstack/ods-jenkins-shared-library, pull requests merged in 2021-01, with the labels that each got.

#544 Typed Options
  .github/workflows/check-docs.sh
  .github/workflows/gradle.yml
  Makefile
  build.gradle
  docs/modules/jenkins-shared-library/partials/odsComponentStageBuildOpenShiftImage.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageBuildOpenShiftImage.adoc.tmpl
  docs/modules/jenkins-shared-library/partials/odsComponentStageImportOpenShiftImage.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageImportOpenShiftImage.adoc.tmpl
  docs/modules/jenkins-shared-library/partials/odsComponentStageRolloutOpenShiftDeployment.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageRolloutOpenShiftDeployment.adoc.tmpl
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSnyk.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSnyk.adoc.tmpl
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSonar.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageScanWithSonar.adoc.tmpl
  docs/modules/jenkins-shared-library/partials/odsComponentStageUploadToNexus.adoc
  docs/modules/jenkins-shared-library/partials/odsComponentStageUploadToNexus.adoc.tmpl
  go.mod
  go.sum
  render-adoc.go
  src/org/ods/component/BuildOpenShiftImageOptions.groovy
  src/org/ods/component/BuildOpenShiftImageStage.groovy
  src/org/ods/component/ImportOpenShiftImageOptions.groovy
  src/org/ods/component/ImportOpenShiftImageStage.groovy
  src/org/ods/component/Options.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentOptions.groovy
  src/org/ods/component/RolloutOpenShiftDeploymentStage.groovy
  src/org/ods/component/ScanWithSnykOptions.groovy
  src/org/ods/component/ScanWithSnykStage.groovy
  src/org/ods/component/ScanWithSonarOptions.groovy
  src/org/ods/component/ScanWithSonarStage.groovy
  src/org/ods/component/Stage.groovy
  src/org/ods/component/UploadToNexusOptions.groovy
  src/org/ods/component/UploadToNexusStage.groovy
  src/org/ods/services/SonarQubeService.groovy
  src/org/ods/util/IPipelineSteps.groovy
  src/org/ods/util/PipelineSteps.groovy
  test/groovy/org/ods/component/StageSpec.groovy
  test/groovy/util/PipelineSteps.groovy
  test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageImportOpenShiftImageSpec.groovy
  test/groovy/vars/OdsComponentStageRolloutOpenShiftDeploymentSpec.groovy
  test/groovy/vars/OdsComponentStageScanWithSnykSpec.groovy
  test/groovy/vars/OdsComponentStageScanWithSonarSpec.groovy
  test/groovy/vars/OdsComponentStageUploadToNexusSpec.groovy
Labels: documentation, enhancement

#553 Add document describing changes in ODS 4
  docs/modules/jenkins-shared-library/partials/update-to-4x.adoc
Labels: documentation

#570 [orchestration] Add beta support for ods-infra type for 3.x
  build.gradle
  src/org/ods/orchestration/DeployStage.groovy
  src/org/ods/orchestration/FinalizeStage.groovy
  src/org/ods/orchestration/Stage.groovy
  src/org/ods/orchestration/scheduler/LeVADocumentScheduler.groovy
  src/org/ods/orchestration/usecase/DocGenUseCase.groovy
  src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
  src/org/ods/orchestration/util/MROPipelineUtil.groovy
  src/org/ods/orchestration/util/PipelineUtil.groovy
  src/org/ods/orchestration/util/Project.groovy
  src/org/ods/services/JenkinsService.groovy
  test/groovy/org/ods/orchestration/scheduler/DocGenSchedulerSpec.groovy
  test/groovy/org/ods/orchestration/usecase/DocGenUseCaseSpec.groovy
  test/groovy/org/ods/orchestration/usecase/LeVADocumentUseCaseSpec.groovy
Labels: enhancement
